name: Build Android APK
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Android
        run: |
          npx eas-cli build --platform android --non-interactive --local --output my-app.apk
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          # यह लाइन Kotlin/Gradle के एरर को कम करने में मदद करेगी
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2048m -Dkotlin.daemon.jvm.options=-Xmx2048m"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Android-APK
          path: my-app.apk
          
